name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Install dependencies
      run: |
       go version
       go get -u "github.com/elastic/go-elasticsearch"
       go get -u "github.com/fsnotify/fsnotify"
       got get -u "github.com/spf13/viper"
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
